services:
  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./apps/api/public:/var/www/html/public
    depends_on:
      - api
  api:
    image: php:8.2-fpm
    working_dir: /var/www/html
    volumes:
      - ./apps/api:/var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ideaholiday_api
      - MYSQL_USER=ideaholiday
      - MYSQL_PASSWORD=ideapass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  db_data:
